apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJtYXlhbmtkZXYwMS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkRwTllYbGhibXRBTVRBd0pRPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson

